### PR TITLE
Add two variables for yml files to README

### PR DESCRIPTION
**Pull request by hillaryj**
# 
Adds two required variables to the README for suggested/template yml config file.

## 🗣 Description

Adds variable names and suggested values for:

- `assessment_data_s3_bucket               = "assessment-data"`
- `assessment_data_import_lambda_s3_bucket = "assessment-data-import-lambda"`

## 💭 Motivation and Context

This helps explain for when a new user is setting up for the first time.

## 🧪 Testing

Docs only.

## 🚥 Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jsf9k** [comment]
@hillaryj, before this PR is reviewed you should
* Create another PR where you pull in the latest upstream changes from the relevant skeleton ([cisagov/skeleton-tf-module](https://github.com/cisagov/skeleton-tf-module) in this case, but check with @mcdonnnj or @dav3r to make sure).  This repo is horrifically out of date, so you may want to get some assistance from @mcdonnnj to bring it into the modern era.
* Get that PR approved and merged
* Merge develop into the branch for _this_ PR

At that point this repo should be building successfully via GitHub Actions.

**Comment by jsf9k** [comment]
Also, the preferred way to update the Terraform variables, providers, etc. is to run 

    terraform-docs markdown --no-escape --no-header . | sed -E 's/`"|"`/`/g'

 in the root directory, then paste that output into the README.  There are two things that you will have to fix:

* `terraform-docs` only puts [octothorpes](https://en.wiktionary.org/wiki/octothorpe) at the beginning of headers.  We prefer the style where headers have opening _and_ closing octothorpes, so you will need to add the closing octothorpes.  If you forget the linters should complain.
* Sometimes `terraform-docs` likes to use the `<pre>` HTML tag instead of using backticks.  If that happens, our linters will reject the commit and you will have to remove the `<pre>` jazz and use backticks instead.

**Comment by jsf9k** [comment]
> @hillaryj, before this PR is reviewed you should
> 
> * Create another PR where you pull in the latest upstream changes from the relevant skeleton ([cisagov/skeleton-tf-module](https://github.com/cisagov/skeleton-tf-module) in this case, but check with @mcdonnnj or @dav3r to make sure).  This repo is horrifically out of date, so you may want to get some assistance from @mcdonnnj to bring it into the modern era.
> * Get that PR approved and merged
> * Merge develop into the branch for _this_ PR
> 
> At that point this repo should be building successfully via GitHub Actions.

The other PR mentioned above is #4.

**Review by jsf9k — APPROVED** [review]
Huzzah!

**Review by dav3r — APPROVED** [review]
🎉

**Pull request merged**
